// src/app/[locale]/layout.tsx

import React, { ReactNode } from 'react';
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import '@/app//globals.css';
import { getServerSession } from 'next-auth';
import NotFound from './not-found';
import SessionProvider from '@/app/components/session/SessionProvider'; // adjusted path
import { routing } from '@/i18n/route';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  params: { locale: string };
}

const RootLayout = async ({
  children,
  params: { locale },
}: RootLayoutProps) => {
  if (!routing.locales.includes(locale)) {
    NotFound();
  }
  let messages;
  try {
    messages = (await import(`@/../messages/${locale}.json`)).default;
  } catch (error) {
    NotFound();
  }

  const session = await getServerSession();
  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body>
        <SessionProvider session={session}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
